# name : Donal howe 
#31/03/2023
# license : GNU LICENSE 3.0
OBJS	= Semaphore.o signal.o
SOURCE	= Semaphore.cpp, signal.cpp
HEADER	= Semaphore.h,
OUT	= SemaphoreFile
CC	 = g++


all: $(OBJS)
	$(CC) -g $(OBJS) -o $(OUT) $(LFLAGS)



	
